/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session and CSRF token
         * @description Always answers 200, signed in or not, so the SPA can fetch a CSRF token before the first sign-in attempt.
         */
        get: operations["getSession"];
        put?: never;
        /** Sign in */
        post: operations["createSession"];
        /** Sign out */
        delete: operations["destroySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active organization, rotating the session */
        post: operations["switchSessionOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's audit trail
         * @description Owner and admin only (ADR 0008).
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite someone to join the organization
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/acceptance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a pending invitation
         * @description No session required (ADR 0003): holding the token is the only credential this action recognizes. The token travels in the body, never the URL, so it cannot leak through request path logging. Signs the accepting user in on success, the same as POST /session.
         */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member from the organization
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        delete: operations["destroyMembership"];
        options?: never;
        head?: never;
        /**
         * Change a member's role
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        patch: operations["updateMembership"];
        trace?: never;
    };
    "/password_resets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Always answers 204 whether or not the email belongs to an account or a demo one (ADR 0007: uniform response); a real, non-demo account receives an email with a single-use link that expires in 20 minutes.
         */
        post: operations["createPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password_resets/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a password reset with its token
         * @description No session is started (ADR 0007): sign in afterwards with the new password. The token travels in the body, never the URL, so it cannot leak through request path logging; it stops working after this succeeds, since it is bound to the password salt it just changed.
         */
        post: operations["completePasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the signed-in user's own password
         * @description Requires the current password; denied to demo users (ADR 0008: an authentication setting). Revokes every other session of the caller, in every organization (ADR 0007), leaving this one alive.
         */
        patch: operations["updatePassword"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            demo: boolean;
        };
        Organization: {
            id: number;
            name: string;
            time_zone: string;
            demo: boolean;
        };
        Membership: {
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
            organization: components["schemas"]["Organization"];
        };
        SessionData: {
            csrf_token: string;
            user: components["schemas"]["User"] | null;
            membership: components["schemas"]["Membership"] | null;
            memberships: components["schemas"]["Membership"][];
        };
        SessionResponseBody: {
            data: components["schemas"]["SessionData"];
        };
        CreateSessionRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @description Required only when the account belongs to more than one organization. */
            organization_id?: number;
        };
        SwitchOrganizationRequest: {
            organization_id: number;
        };
        Error: {
            code: string;
            message: string;
            details: {
                [key: string]: unknown;
            };
            request_id: string | null;
        };
        ErrorResponseBody: {
            error: components["schemas"]["Error"];
        };
        Meta: {
            page: number;
            per_page: number;
            total: number;
        };
        AuditEvent: {
            id: number;
            action: string;
            subject_type: string;
            subject_id: number;
            field_changes: {
                [key: string]: unknown;
            };
            actor: components["schemas"]["User"];
            /** Format: date-time */
            created_at: string;
        };
        AuditEventListResponseBody: {
            data: components["schemas"]["AuditEvent"][];
            meta: components["schemas"]["Meta"];
        };
        CreateInvitationRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
        };
        Invitation: {
            id: number;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
            /** Format: date-time */
            expires_at: string;
            /** @description The raw invitation token. Shown only in this response; only its digest is stored. */
            token: string;
        };
        InvitationResponseBody: {
            data: components["schemas"]["Invitation"];
        };
        AcceptInvitationRequest: {
            token: string;
            /** @description Required when the invited email has no account yet. */
            name?: string;
            /** @description Required when the invited email has no account yet. */
            password?: string;
        };
        UpdateMembershipRequest: {
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
        };
        Member: {
            id: number;
            user: components["schemas"]["User"];
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
        };
        MemberResponseBody: {
            data: components["schemas"]["Member"];
        };
        CreatePasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        CompletePasswordResetRequest: {
            token: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            password: string;
        };
    };
    responses: {
        /** @description The current session, if any, and a CSRF token. */
        SessionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SessionResponseBody"];
            };
        };
        /** @description An error in the shared envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponseBody"];
            };
        };
        /** @description A page of the audit trail. */
        AuditEventListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuditEventListResponseBody"];
            };
        };
        /** @description A newly issued invitation, with its one-time token. */
        InvitationResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InvitationResponseBody"];
            };
        };
        /** @description A member of the current organization. */
        MemberResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MemberResponseBody"];
            };
        };
    };
    parameters: {
        /** @description The csrf_token from the most recent GET or POST /session response. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionResponse"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            201: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    destroySession: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    switchSessionOrganization: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrganizationRequest"];
            };
        };
        responses: {
            200: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuditEventListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            201: components["responses"]["InvitationResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            201: components["responses"]["SessionResponse"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    destroyMembership: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    updateMembership: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembershipRequest"];
            };
        };
        responses: {
            200: components["responses"]["MemberResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createPasswordReset: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePasswordResetRequest"];
            };
        };
        responses: {
            /** @description The request was accepted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    completePasswordReset: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletePasswordResetRequest"];
            };
        };
        responses: {
            /** @description The password was reset. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    updatePassword: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The password was changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
}
