/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session and CSRF token
         * @description Always answers 200, signed in or not, so the SPA can fetch a CSRF token before the first sign-in attempt.
         */
        get: operations["getSession"];
        put?: never;
        /** Sign in */
        post: operations["createSession"];
        /** Sign out */
        delete: operations["destroySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active organization, rotating the session */
        post: operations["switchSessionOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            demo: boolean;
        };
        Organization: {
            id: number;
            name: string;
            time_zone: string;
            demo: boolean;
        };
        Membership: {
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
            organization: components["schemas"]["Organization"];
        };
        SessionData: {
            csrf_token: string;
            user: components["schemas"]["User"] | null;
            membership: components["schemas"]["Membership"] | null;
            memberships: components["schemas"]["Membership"][];
        };
        SessionResponseBody: {
            data: components["schemas"]["SessionData"];
        };
        CreateSessionRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @description Required only when the account belongs to more than one organization. */
            organization_id?: number;
        };
        SwitchOrganizationRequest: {
            organization_id: number;
        };
        Error: {
            code: string;
            message: string;
            details: {
                [key: string]: unknown;
            };
            request_id: string | null;
        };
        ErrorResponseBody: {
            error: components["schemas"]["Error"];
        };
    };
    responses: {
        /** @description The current session, if any, and a CSRF token. */
        SessionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SessionResponseBody"];
            };
        };
        /** @description An error in the shared envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponseBody"];
            };
        };
    };
    parameters: {
        /** @description The csrf_token from the most recent GET or POST /session response. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionResponse"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            201: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    destroySession: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    switchSessionOrganization: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrganizationRequest"];
            };
        };
        responses: {
            200: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
}
