/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session and CSRF token
         * @description Always answers 200, signed in or not, so the SPA can fetch a CSRF token before the first sign-in attempt.
         */
        get: operations["getSession"];
        put?: never;
        /** Sign in */
        post: operations["createSession"];
        /** Sign out */
        delete: operations["destroySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active organization, rotating the session */
        post: operations["switchSessionOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's audit trail
         * @description Owner and admin only (ADR 0008).
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's units of measure
         * @description Every role can read (ADR 0008); owner, admin and purchasing can also write.
         */
        get: operations["listUnits"];
        put?: never;
        /**
         * Create a unit of measure
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        post: operations["createUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show a unit of measure
         * @description Every role can read (ADR 0008).
         */
        get: operations["showUnit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a unit of measure
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        patch: operations["updateUnit"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's product categories
         * @description Every role can read (ADR 0008); owner, admin and purchasing can also write.
         */
        get: operations["listCategories"];
        put?: never;
        /**
         * Create a product category
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show a product category
         * @description Every role can read (ADR 0008).
         */
        get: operations["showCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a product category
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's products
         * @description Every role can read (ADR 0008); owner, admin and purchasing can also write.
         */
        get: operations["listProducts"];
        put?: never;
        /**
         * Create a product
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show a product
         * @description Every role can read (ADR 0008).
         */
        get: operations["showProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a product
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's warehouses
         * @description Every role can read (ADR 0008); owner, admin and purchasing can also write.
         */
        get: operations["listWarehouses"];
        put?: never;
        /**
         * Create a warehouse
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        post: operations["createWarehouse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show a warehouse
         * @description Every role can read (ADR 0008).
         */
        get: operations["showWarehouse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a warehouse
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        patch: operations["updateWarehouse"];
        trace?: never;
    };
    "/stock_balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the stock position, one row per product and warehouse
         * @description Every role can read (ADR 0016).
         */
        get: operations["listStockBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock_movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the movement ledger, newest first
         * @description Every role but sales can read (ADR 0016); sales sees balances only.
         */
        get: operations["listStockMovements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock_adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a count adjustment
         * @description Sets the stock of a product in a warehouse to the counted quantity and records the difference as one ledger movement (ADR 0016). Owner, admin and purchasing only (ADR 0008). A count equal to the balance writes no movement and answers 200 with a null movement. The reason must agree with the direction: loss, damage, theft and expiry decrease stock; found and opening_balance increase it, and opening_balance only for a balance with no history.
         */
        post: operations["createStockAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase_orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List purchase orders, newest number first
         * @description Owner, admin, purchasing, finance and read_only can read; sales has no access (ADR 0017, ADR 0008).
         */
        get: operations["listPurchaseOrders"];
        put?: never;
        /**
         * Create a draft purchase order
         * @description Owner, admin and purchasing only. Copies the supplier and each product as they are now (ADR 0015), works out every line's amounts and the order's total, and numbers the order. Amounts are stored; a client never computes them.
         */
        post: operations["createPurchaseOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase_orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show a purchase order with its lines
         * @description The supplier's CPF is masked for a role that may not see a partner's in full (ADR 0014).
         */
        get: operations["showPurchaseOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Replace a draft purchase order's supplier, terms, note and lines
         * @description Owner, admin and purchasing only, and only while the order is a draft. Send the revision that was read; a newer one on the server answers 409 stale and writes nothing (ADR 0015).
         */
        patch: operations["updatePurchaseOrder"];
        trace?: never;
    };
    "/purchase_orders/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a draft purchase order
         * @description Owner, admin and purchasing only. The approver sends the revision they saw, so an edit made in between answers 409 stale instead of being approved unseen. Approval checks the order can be received and freezes what it copies.
         */
        post: operations["approvePurchaseOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase_orders/{id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a purchase order
         * @description Owner, admin and purchasing only. A draft or approved order ends; a partially received one is closed at what has been received. A received or cancelled order answers 409 invalid_transition.
         */
        post: operations["cancelPurchaseOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's partners
         * @description Every role can read (ADR 0008); owner, admin and purchasing can also write.
         */
        get: operations["listPartners"];
        put?: never;
        /**
         * Create a partner
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        post: operations["createPartner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show a partner
         * @description Every role can read (ADR 0008).
         */
        get: operations["showPartner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a partner
         * @description Owner, admin and purchasing only (ADR 0008).
         */
        patch: operations["updatePartner"];
        trace?: never;
    };
    "/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's pending invitations
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        get: operations["listInvitations"];
        put?: never;
        /**
         * Invite someone to join the organization
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/acceptance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a pending invitation
         * @description No session required (ADR 0003): holding the token is the only credential this action recognizes. The token travels in the body, never the URL, so it cannot leak through request path logging. Signs the accepting user in on success, the same as POST /session.
         */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel a pending invitation
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        delete: operations["destroyInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the current organization's members
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        get: operations["listMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member from the organization
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        delete: operations["destroyMembership"];
        options?: never;
        head?: never;
        /**
         * Change a member's role
         * @description Owner and admin only; denied to demo users regardless of role (ADR 0008).
         */
        patch: operations["updateMembership"];
        trace?: never;
    };
    "/password_resets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Always answers 204 whether or not the email belongs to an account or a demo one (ADR 0007: uniform response); a real, non-demo account receives an email with a single-use link that expires in 20 minutes.
         */
        post: operations["createPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password_resets/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a password reset with its token
         * @description No session is started (ADR 0007): sign in afterwards with the new password. The token travels in the body, never the URL, so it cannot leak through request path logging; it stops working after this succeeds, since it is bound to the password salt it just changed.
         */
        post: operations["completePasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the signed-in user's own password
         * @description Requires the current password; denied to demo users (ADR 0008: an authentication setting). Revokes every other session of the caller, in every organization (ADR 0007), leaving this one alive.
         */
        patch: operations["updatePassword"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            demo: boolean;
        };
        Organization: {
            id: number;
            name: string;
            time_zone: string;
            demo: boolean;
        };
        Membership: {
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
            organization: components["schemas"]["Organization"];
        };
        SessionData: {
            csrf_token: string;
            user: components["schemas"]["User"] | null;
            membership: components["schemas"]["Membership"] | null;
            memberships: components["schemas"]["Membership"][];
        };
        SessionResponseBody: {
            data: components["schemas"]["SessionData"];
        };
        CreateSessionRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @description Required only when the account belongs to more than one organization. */
            organization_id?: number;
        };
        SwitchOrganizationRequest: {
            organization_id: number;
        };
        Error: {
            code: string;
            message: string;
            details: {
                [key: string]: unknown;
            };
            request_id: string | null;
        };
        ErrorResponseBody: {
            error: components["schemas"]["Error"];
        };
        Meta: {
            page: number;
            per_page: number;
            total: number;
        };
        AuditEvent: {
            id: number;
            action: string;
            subject_type: string;
            subject_id: number;
            field_changes: {
                [key: string]: unknown;
            };
            actor: components["schemas"]["User"];
            /** Format: date-time */
            created_at: string;
        };
        AuditEventListResponseBody: {
            data: components["schemas"]["AuditEvent"][];
            meta: components["schemas"]["Meta"];
        };
        CreateInvitationRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
        };
        Invitation: {
            id: number;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
            /** Format: date-time */
            expires_at: string;
            /** @description The raw invitation token. Shown only in this response; only its digest is stored. */
            token: string;
        };
        InvitationResponseBody: {
            data: components["schemas"]["Invitation"];
        };
        AcceptInvitationRequest: {
            token: string;
            /** @description Required when the invited email has no account yet. */
            name?: string;
            /** @description Required when the invited email has no account yet. */
            password?: string;
        };
        UpdateMembershipRequest: {
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
        };
        Member: {
            id: number;
            user: components["schemas"]["User"];
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
        };
        MemberResponseBody: {
            data: components["schemas"]["Member"];
        };
        MemberListResponseBody: {
            data: components["schemas"]["Member"][];
            meta: components["schemas"]["Meta"];
        };
        PendingInvitation: {
            id: number;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "purchasing" | "sales" | "finance" | "read_only";
            invited_by: components["schemas"]["User"];
            /** Format: date-time */
            expires_at: string;
        };
        PendingInvitationListResponseBody: {
            data: components["schemas"]["PendingInvitation"][];
            meta: components["schemas"]["Meta"];
        };
        CreatePasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        CompletePasswordResetRequest: {
            token: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            password: string;
        };
        Unit: {
            id: number;
            code: string;
            name: string;
            active: boolean;
        };
        UnitResponseBody: {
            data: components["schemas"]["Unit"];
        };
        UnitListResponseBody: {
            data: components["schemas"]["Unit"][];
            meta: components["schemas"]["Meta"];
        };
        CreateUnitRequest: {
            code: string;
            name: string;
        };
        UpdateUnitRequest: {
            code: string;
            name: string;
            active: boolean;
        };
        Category: {
            id: number;
            name: string;
            active: boolean;
        };
        CategoryResponseBody: {
            data: components["schemas"]["Category"];
        };
        CategoryListResponseBody: {
            data: components["schemas"]["Category"][];
            meta: components["schemas"]["Meta"];
        };
        CreateCategoryRequest: {
            name: string;
        };
        UpdateCategoryRequest: {
            name: string;
            active: boolean;
        };
        UnitConversion: {
            purchase_unit: components["schemas"]["Unit"];
            /** @description Decimal string, always 6 places (ADR 0006). Stock quantity = purchase quantity x factor. */
            factor: string;
        };
        Product: {
            id: number;
            sku: string;
            name: string;
            active: boolean;
            /** @description Counts the successful edits of this record (ADR 0015). Send back the value that was read; if the record changed since, the answer is 409 stale and nothing is written. */
            revision: number;
            category: components["schemas"]["Category"] | null;
            stock_unit: components["schemas"]["Unit"];
            unit_conversion: components["schemas"]["UnitConversion"];
        };
        ProductResponseBody: {
            data: components["schemas"]["Product"];
        };
        ProductListResponseBody: {
            data: components["schemas"]["Product"][];
            meta: components["schemas"]["Meta"];
        };
        CreateProductRequest: {
            sku: string;
            name: string;
            category_id?: number | null;
            stock_unit_id: number;
            purchase_unit_id: number;
            /** @description Decimal string, greater than zero, below 1000000000, at most 6 places (ADR 0006). More places or a larger value is a validation_failed (too_many_decimals, less_than), never a rounding. */
            factor: string;
        };
        UpdateProductRequest: {
            sku: string;
            name: string;
            category_id?: number | null;
            /** @description Must equal the product's current stock unit. A different one is a validation_failed with the kind immutable on stock_unit (ADR 0015). */
            stock_unit_id: number;
            purchase_unit_id: number;
            /** @description Decimal string, greater than zero, below 1000000000, at most 6 places (ADR 0006). More places or a larger value is a validation_failed (too_many_decimals, less_than), never a rounding. */
            factor: string;
            active: boolean;
            /** @description The revision that was read; a newer one on the server answers 409 stale (ADR 0015). */
            revision: number;
        };
        Warehouse: {
            id: number;
            name: string;
            active: boolean;
        };
        WarehouseResponseBody: {
            data: components["schemas"]["Warehouse"];
        };
        WarehouseListResponseBody: {
            data: components["schemas"]["Warehouse"][];
            meta: components["schemas"]["Meta"];
        };
        CreateWarehouseRequest: {
            name: string;
        };
        UpdateWarehouseRequest: {
            name: string;
            active: boolean;
        };
        /** @enum {string} */
        AdjustmentReason: "opening_balance" | "count" | "loss" | "damage" | "theft" | "expiry" | "found" | "other";
        /** @description A product as a balance or a movement refers to it. */
        ProductReference: {
            id: number;
            sku: string;
            name: string;
            stock_unit: components["schemas"]["Unit"];
        };
        StockBalance: {
            id: number;
            product: components["schemas"]["ProductReference"];
            warehouse: components["schemas"]["Warehouse"];
            /** @description Decimal string with 3 places, in the product's stock unit (ADR 0006). */
            on_hand: string;
            reserved: string;
            /** @description on_hand minus reserved, computed by the API. */
            available: string;
            /** @description The inventory value of on_hand, in cents (ADR 0006). Null for a role that may not see what stock is worth or cost (sales, ADR 0016). */
            value_cents: number | null;
            /** @enum {string} */
            currency: "BRL";
            /** @description Cost per stock unit of the latest costed entry, in cents, always 6 places. Null when value_cents is. */
            last_unit_cost_cents: string | null;
        };
        StockMovement: {
            id: number;
            /** @enum {string} */
            kind: "adjustment";
            reason: components["schemas"]["AdjustmentReason"] | null;
            note: string | null;
            product: components["schemas"]["ProductReference"];
            warehouse: components["schemas"]["Warehouse"];
            /** @description Signed, and a negative quantity takes stock out. */
            quantity: string;
            /** @description Signed like quantity. */
            value_cents: number;
            /** @enum {string} */
            currency: "BRL";
            on_hand_after: string;
            value_after_cents: number;
            actor: {
                id: number;
                name: string;
            };
            /** Format: date-time */
            created_at: string;
        };
        StockBalanceListResponseBody: {
            data: components["schemas"]["StockBalance"][];
            meta: components["schemas"]["Meta"];
        };
        StockMovementListResponseBody: {
            data: components["schemas"]["StockMovement"][];
            meta: components["schemas"]["Meta"];
        };
        StockAdjustmentResponseBody: {
            data: {
                movement: components["schemas"]["StockMovement"] | null;
                balance: components["schemas"]["StockBalance"];
            };
        };
        StockAdjustmentRequest: {
            product_id: number;
            warehouse_id: number;
            /** @description The quantity actually counted, in the product's stock unit, at most 3 places. The API computes the difference from the balance under its lock; the client never does. */
            counted_quantity: string;
            /** @description The balance's on_hand as the client last saw it ("0.000" when it had no balance). A count is an observation at a moment: if a sale or a receipt moved the balance since, the count is refused with 409 stale, and error details carry current_on_hand (ADR 0016). */
            expected_on_hand: string;
            reason: components["schemas"]["AdjustmentReason"];
            note?: string;
            /** @description Cost per stock unit in cents (a decimal string, since a unit can cost a fraction of a cent), at most 6 places, for an increase. Required when the balance has no average or last cost to value it with (kind required on unit_cost_cents); not allowed for a decrease (ADR 0016). */
            unit_cost_cents?: string;
        };
        /** @enum {string} */
        PurchaseOrderStatus: "draft" | "approved" | "partially_received" | "received" | "cancelled";
        PurchaseOrderSummary: {
            id: number;
            number: number;
            status: components["schemas"]["PurchaseOrderStatus"];
            supplier: {
                id: number;
                name: string;
            };
            total_cents: number;
            /** @enum {string} */
            currency: "BRL";
            /** Format: date-time */
            created_at: string;
        };
        PurchaseOrderLine: {
            id: number;
            position: number;
            product: {
                id: number;
                sku: string;
                name: string;
            };
            purchase_unit_code: string;
            stock_unit_code: string;
            /** @description Stock units per purchase unit, as copied from the product (ADR 0015). */
            factor: string;
            /** @description In purchase units. */
            quantity: string;
            received_quantity: string;
            remaining_quantity: string;
            /** @description Per purchase unit. */
            unit_price_cents: number;
            /** @description Basis points, 0 to 10000. */
            discount_bp: number;
            gross_cents: number;
            discount_cents: number;
            net_cents: number;
        };
        PurchaseOrder: {
            id: number;
            number: number;
            status: components["schemas"]["PurchaseOrderStatus"];
            supplier: {
                id: number;
                name: string;
                /** @enum {string} */
                document_type: "cpf" | "cnpj";
                /** @description Copied when the order was created; a CPF is masked when personal_data_visible is false (ADR 0014). */
                document_number: string;
            };
            installments: number;
            first_due_days: number;
            interval_days: number;
            note: string | null;
            /** @description The sum of the lines' net amounts, stored. */
            total_cents: number;
            /** @enum {string} */
            currency: "BRL";
            /** @description Send it back when editing or approving a draft (ADR 0015). */
            revision: number;
            personal_data_visible: boolean;
            /** Format: date-time */
            approved_at: string | null;
            /** Format: date-time */
            cancelled_at: string | null;
            /** Format: date-time */
            created_at: string;
            lines: components["schemas"]["PurchaseOrderLine"][];
        };
        PurchaseOrderResponseBody: {
            data: components["schemas"]["PurchaseOrder"];
        };
        PurchaseOrderListResponseBody: {
            data: components["schemas"]["PurchaseOrderSummary"][];
            meta: components["schemas"]["Meta"];
        };
        PurchaseOrderLineInput: {
            product_id: number;
            /** @description In purchase units, at most 3 places. */
            quantity: string;
            /** @description Per purchase unit. */
            unit_price_cents: number;
            /** @description Basis points off the line's gross; 0 when omitted. */
            discount_bp?: number;
        };
        CreatePurchaseOrderRequest: {
            supplier_id: number;
            /** @description How many installments each receipt's payable is split in; 1 when omitted. */
            installments?: number;
            /** @description Days from the receipt to the first due date; 30 when omitted. */
            first_due_days?: number;
            /** @description Days between installments; 30 when omitted. */
            interval_days?: number;
            note?: string;
            lines: components["schemas"]["PurchaseOrderLineInput"][];
        };
        UpdatePurchaseOrderRequest: {
            supplier_id: number;
            installments?: number;
            first_due_days?: number;
            interval_days?: number;
            note?: string;
            lines: components["schemas"]["PurchaseOrderLineInput"][];
            /** @description The revision that was read; a newer one answers 409 stale (ADR 0015). */
            revision: number;
        };
        PurchaseOrderRevisionRequest: {
            /** @description The revision the approver saw; a newer one answers 409 stale (ADR 0015). */
            revision: number;
        };
        /** @description A partner as listed (ADR 0014). The CPF is masked for every role and e-mail and phone are not part of a list; the full record comes from GET /partners/{id}. */
        PartnerSummary: {
            id: number;
            name: string;
            /** @enum {string} */
            document_type: "cpf" | "cnpj";
            /** @description A CPF with only the middle six digits visible ("***982247**"); a CNPJ in full, since it is public registry data. */
            document_number: string;
            customer: boolean;
            supplier: boolean;
            active: boolean;
        };
        Partner: {
            id: number;
            name: string;
            /** @enum {string} */
            document_type: "cpf" | "cnpj";
            /** @description Digits only for a CPF; digits and upper-case letters for a CNPJ (ADR 0012, alphanumeric since July 2026). No punctuation. A CPF is masked as in PartnerSummary when personal_data_visible is false. */
            document_number: string;
            customer: boolean;
            supplier: boolean;
            /** @description Always null when personal_data_visible is false. */
            email: string | null;
            /** @description Always null when personal_data_visible is false. */
            phone: string | null;
            /** @description False when the caller's role may not see this partner's CPF, e-mail and phone in full (ADR 0014: read_only). */
            personal_data_visible: boolean;
            active: boolean;
            /** @description Counts the successful edits of this record (ADR 0015). Send back the value that was read; if the record changed since, the answer is 409 stale and nothing is written. */
            revision: number;
        };
        PartnerResponseBody: {
            data: components["schemas"]["Partner"];
        };
        PartnerListResponseBody: {
            data: components["schemas"]["PartnerSummary"][];
            meta: components["schemas"]["Meta"];
        };
        CreatePartnerRequest: {
            name: string;
            /** @enum {string} */
            document_type: "cpf" | "cnpj";
            document_number: string;
            customer: boolean;
            supplier: boolean;
            email?: string;
            phone?: string;
        };
        UpdatePartnerRequest: {
            name: string;
            /** @enum {string} */
            document_type: "cpf" | "cnpj";
            document_number: string;
            customer: boolean;
            supplier: boolean;
            email?: string;
            phone?: string;
            active: boolean;
            /** @description The revision that was read; a newer one on the server answers 409 stale (ADR 0015). */
            revision: number;
        };
    };
    responses: {
        /** @description The current session, if any, and a CSRF token. */
        SessionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SessionResponseBody"];
            };
        };
        /** @description An error in the shared envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponseBody"];
            };
        };
        /** @description A page of the audit trail. */
        AuditEventListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuditEventListResponseBody"];
            };
        };
        /** @description A newly issued invitation, with its one-time token. */
        InvitationResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InvitationResponseBody"];
            };
        };
        /** @description A member of the current organization. */
        MemberResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MemberResponseBody"];
            };
        };
        /** @description A page of the current organization's members. */
        MemberListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MemberListResponseBody"];
            };
        };
        /** @description A page of the current organization's pending invitations. */
        PendingInvitationListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PendingInvitationListResponseBody"];
            };
        };
        /** @description A unit of measure. */
        UnitResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnitResponseBody"];
            };
        };
        /** @description A page of the current organization's units of measure. */
        UnitListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnitListResponseBody"];
            };
        };
        /** @description A product category. */
        CategoryResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CategoryResponseBody"];
            };
        };
        /** @description A page of the current organization's product categories. */
        CategoryListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CategoryListResponseBody"];
            };
        };
        /** @description A product. */
        ProductResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProductResponseBody"];
            };
        };
        /** @description A page of the current organization's products. */
        ProductListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProductListResponseBody"];
            };
        };
        /** @description A warehouse. */
        WarehouseResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WarehouseResponseBody"];
            };
        };
        /** @description A page of the current organization's warehouses. */
        WarehouseListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WarehouseListResponseBody"];
            };
        };
        /** @description A page of the stock position. */
        StockBalanceListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StockBalanceListResponseBody"];
            };
        };
        /** @description A page of the movement ledger, newest first. */
        StockMovementListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StockMovementListResponseBody"];
            };
        };
        /** @description The movement that was written, or null when the count matched, and the balance after it. */
        StockAdjustmentResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StockAdjustmentResponseBody"];
            };
        };
        /** @description A purchase order with its lines. */
        PurchaseOrderResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PurchaseOrderResponseBody"];
            };
        };
        /** @description A page of purchase orders. */
        PurchaseOrderListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PurchaseOrderListResponseBody"];
            };
        };
        /** @description A partner. */
        PartnerResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PartnerResponseBody"];
            };
        };
        /** @description A page of the current organization's partners. */
        PartnerListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PartnerListResponseBody"];
            };
        };
    };
    parameters: {
        /** @description The csrf_token from the most recent GET or POST /session response. */
        CsrfToken: string;
        /** @description A client-generated key of 8 to 100 characters (letters, digits and . _ : -), one per user intent (ADR 0005). Repeating a request with the same key and the same body replays its result without a second effect; the same key with another body is a 422 idempotency_key_reused. Only successes are remembered, so a failed attempt can be retried. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionResponse"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            201: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    destroySession: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    switchSessionOrganization: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrganizationRequest"];
            };
        };
        responses: {
            200: components["responses"]["SessionResponse"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuditEventListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listUnits: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["UnitListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createUnit: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUnitRequest"];
            };
        };
        responses: {
            201: components["responses"]["UnitResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    showUnit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["UnitResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateUnit: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUnitRequest"];
            };
        };
        responses: {
            200: components["responses"]["UnitResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CategoryListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            201: components["responses"]["CategoryResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    showCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CategoryResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            200: components["responses"]["CategoryResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                category_id?: number;
                active?: boolean;
                /** @description Case-insensitive search over name and sku. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProductListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            201: components["responses"]["ProductResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    showProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProductResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            200: components["responses"]["ProductResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listWarehouses: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WarehouseListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createWarehouse: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWarehouseRequest"];
            };
        };
        responses: {
            201: components["responses"]["WarehouseResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    showWarehouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["WarehouseResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateWarehouse: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWarehouseRequest"];
            };
        };
        responses: {
            200: components["responses"]["WarehouseResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listStockBalances: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                warehouse_id?: number;
                product_id?: number;
                /** @description Searches the product's name and sku. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StockBalanceListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listStockMovements: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                warehouse_id?: number;
                product_id?: number;
                reason?: components["schemas"]["AdjustmentReason"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StockMovementListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createStockAdjustment: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description A client-generated key of 8 to 100 characters (letters, digits and . _ : -), one per user intent (ADR 0005). Repeating a request with the same key and the same body replays its result without a second effect; the same key with another body is a 422 idempotency_key_reused. Only successes are remembered, so a failed attempt can be retried. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockAdjustmentRequest"];
            };
        };
        responses: {
            200: components["responses"]["StockAdjustmentResponse"];
            201: components["responses"]["StockAdjustmentResponse"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    listPurchaseOrders: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                status?: components["schemas"]["PurchaseOrderStatus"];
                supplier_id?: number;
                /** @description Matches the order number or the supplier's name. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PurchaseOrderListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createPurchaseOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchaseOrderRequest"];
            };
        };
        responses: {
            201: components["responses"]["PurchaseOrderResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    showPurchaseOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PurchaseOrderResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updatePurchaseOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePurchaseOrderRequest"];
            };
        };
        responses: {
            200: components["responses"]["PurchaseOrderResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    approvePurchaseOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseOrderRevisionRequest"];
            };
        };
        responses: {
            200: components["responses"]["PurchaseOrderResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    cancelPurchaseOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PurchaseOrderResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listPartners: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                customer?: boolean;
                supplier?: boolean;
                active?: boolean;
                /** @description Case-insensitive search over name. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PartnerListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createPartner: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePartnerRequest"];
            };
        };
        responses: {
            201: components["responses"]["PartnerResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    showPartner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PartnerResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updatePartner: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePartnerRequest"];
            };
        };
        responses: {
            200: components["responses"]["PartnerResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listInvitations: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PendingInvitationListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            201: components["responses"]["InvitationResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            201: components["responses"]["SessionResponse"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    destroyInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invitation was cancelled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listMemberships: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MemberListResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    destroyMembership: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    updateMembership: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMembershipRequest"];
            };
        };
        responses: {
            200: components["responses"]["MemberResponse"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createPasswordReset: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePasswordResetRequest"];
            };
        };
        responses: {
            /** @description The request was accepted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    completePasswordReset: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletePasswordResetRequest"];
            };
        };
        responses: {
            /** @description The password was reset. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    updatePassword: {
        parameters: {
            query?: never;
            header: {
                /** @description The csrf_token from the most recent GET or POST /session response. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The password was changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
}
