default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 3).to_i + ENV.fetch("JOB_THREADS", 3).to_i + 3 %>

development: &development
  <<: *default
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5433) %>
  username: <%= ENV.fetch("PGUSER", "alicerce") %>
  password: <%= ENV.fetch("PGPASSWORD", "alicerce") %>
  database: alicerce_development

test:
  <<: *development
  database: alicerce_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
